### ISSUE TITLE
Validic::Client#create_sleep - Validic::Error::UnprocessableEntity: 422: Timestamp does not meet format specification or not in UTC time

### ISSUE THREAD

**Issue by topher6345** [Validic/validic#14]
I've tried sending the timestamp field in the following formats and I get the same error each time.

The documentation here 

https://validic.com/validic-connect

specifies that the date be sent as a ISO8601 string
 
## ISO
```ruby
created_at.iso8601(9)
=> "2015-04-09T11:52:46.509864-07:00"
```

I also tried the following formats: 

## Ruby DateTime
```ruby
created_at.to_s
=> "2015-04-09 11:52:46 -0700"
```

## UTC
```ruby
created_at.utc
=> "2015-04-09 18:52:46 UTC"
```

**Comment by topher6345** [comment]
I tried sending the request via Postman, same error for all 3 formats. This is a blocker for our push integration.

**Comment by jjlangholtz** [comment]
The .iso8601 method without any arguments should do the trick:

```ruby
Time.now.iso8601
=> "2015-04-09T16:11:52-04:00"
```

If this doesn't solve the issue can you elaborate on which method on the gem you are using?

**Comment by topher6345** [comment]
hmm, I got the 

`validic (0.4.1)`

```ruby
options = {
  api_version:     'v1',
  access_token:    ENV['VALIDIC_PUSH_ACCESS_TOKEN'],
  organization_id: ENV['VALIDIC_PUSH_ORGANIZATION_ID']
}
@client = Validic::Client.new options
```

```ruby
@client.create_sleep {
 :user_id=>"asdfjkl;", # obfuscated for privacy
 :timestamp=>"2015-04-09T13:48:23-07:00",
 :utc_offset=>"-7:00",
 :awake=>nil,
 :deep=>nil,
 :light=>nil,
 :rem=>nil,
 :times_woken=>nil,
 :total_sleep=>28800.0,
 :sleep_id=>15,
 :extra=>{:quality=>"Good"}}
```

```ruby
Validic::Error::UnprocessableEntity: 422: Timestamp does not meet format specification or not in UTC time
from ~/.rvm/gems/ruby-2.1.5/gems/validic-0.4.1/lib/validic/rest/request.rb:90:in `request'
```

**Comment by jjlangholtz** [comment]
After taking a closer look this API requires the iso8601 string to be in UTC in this format:

(note the +00:00 offset)
```ruby
"2015-04-09T20:58:35+00:00"
```

One way to accomplish this would be:
```ruby
DateTime.now.new_offset.iso8601
```

Alternatively, you can use strftime to format depending on the requirements of your application. Sorry for the confusion!

**Comment by topher6345** [comment]
That worked!

`created_at.to_datetime.new_offset.iso8601`

is what ended up working
