### ISSUE TITLE
undefined method `each' When testing sleep with webmock - validic gem version 0.4.1

### ISSUE THREAD

**Issue by topher6345** [Validic/validic#16]
Context: I'm in the process of writing unit tests for my app to handle the various responses returned from the validic API.

When I call 
```ruby
@client.create_sleep @sleep
```
I get the following error in my tests:

```
#<NoMethodError: undefined method `each' for "sleep":String>
~/.rvm/gems/ruby-2.1.5/gems/validic-0.4.1/lib/validic/utils.rb:5:in `attributes_builder'
~/.rvm/gems/ruby-2.1.5/gems/validic-0.4.1/lib/validic/sleep.rb:5:in `initialize'
~/.rvm/gems/ruby-2.1.5/gems/validic-0.4.1/lib/validic/rest/sleep.rb:17:in `new'
~/.rvm/gems/ruby-2.1.5/gems/validic-0.4.1/lib/validic/rest/sleep.rb:17:in `create_sleep'
```
My theory is that the problem lies in this line:
 
```ruby
# validic-0.4.1/lib/validic/rest/sleep.rb:16
response = post_request(:sleep, options)
Validic::Sleep.new(response['sleep'])
```
In my tests it looks like `response` is stubbed as a string, is this the proper format?

Here is my stubbed request using webmock:

```ruby
def stubbed_request
    request = stub_request(
      :post, "https://api.validic.com/v1/organizations/#{ENV['VALIDIC_PUSH_ORGANIZATION_ID']}/sleep.json")
    request.with(:body => body, :headers => headers)
    request.to_return(:status => 200, :body => response_body.to_json, :headers => {})
  end

  def response_body
  {
    "code"=>201,
     "message"=>"Ok",
     "sleep"=>{
        "timestamp"=> @sleep.created_at.to_datetime.new_offset.iso8601,
        "utc_offset"=>"-7:00",
        "awake"=>nil,
        "deep"=>nil,
        "light"=>nil,
        "rem"=>nil,
        "times_woken"=>nil,
        "total_sleep"=>28800.0,
        "activity_id"=>255050412,
        "extra"=>{"quality"=>"3"},
        "source"=>"sample_app",
        "source_name"=>"Sample App",
        "last_updated"=>"2013-03-10T07:12:16+00:00"}}
  end
  ```

**Comment by topher6345** [comment]
I just confirmed that this can be isolated to the 0.4.1 release. I rolled back to 0.3.3 and I don't have this problem with webmock anymore

**Comment by allcentury** [comment]
Thanks again for letting us know about potential issues like this, we really appreciate it.

Response should be a hash because at this point the gem has parsed the JSON.  To give you some context, we use web mock in our spec suite too and I've updated an example locally to showcase.

Here's what response is right before we pass it into the `Validic::Sleep.new`

```ruby
From: /Users/anthonyross/validic/validic/lib/validic/rest/sleep.rb @ line 17 Validic::REST::Sleep#create_sleep:

    13: def create_sleep(options = {})
    14:   user_id = options.delete(:user_id)
    15:   options = { user_id: user_id, sleep: options }
    16:   response = post_request(:sleep, options)
 => 17:   binding.pry
    18:   Validic::Sleep.new(response['sleep'])
    19: end

[1] pry(#<Validic::Client>)> response
=> {"code"=>201,
 "message"=>"Ok",
 "sleep"=>
  {"_id"=>"51552cddfded0807c4000096",
   "timestamp"=>"2013-03-10T07:12:16+00:00",
   "utc_offset"=>"+00:00",
   "awake"=>34,
   "deep"=>234,
   "light"=>94,
   "rem"=>115,
   "times_woken"=>4,
   "total_sleep"=>477,
   "source"=>"sample_app",
   "source_name"=>"Sample App",
   "last_updated"=>"2013-03-10T07:12:16+00:00"},
 "source"=>"sample_app",
 "source_name"=>"Sample App",
 "last_updated"=>"2013-03-10T07:12:16+00:00"}
[2] pry(#<Validic::Client>)> response.class
=> Hash
```

**Comment by topher6345** [comment]
The problem is related to webmock not allowing hashes as a response body. I'm gonna skip all the tests I've written that use the validic API gem. 

Can we continue this conversation about how to effectively unit test portions of my app that use the validic api?

**Comment by allcentury** [comment]
I see, well hopefully these gem changes will simplify your tests.  Previously you were having to stub out the responses from the API but that's no longer necessary as we're already testing that in the gem itself.  What I'd recommend in your test is to stub out the `Validic::Client` like this:


```ruby
  it 'fetches data' do
    @fitness = Validic::Fitness.new(steps: 1.5, distance: 0.5)
    @client = double("Validic::Client", get_fitness: @fitness)
    allow(Validic::Client).to receive(:new).and_return @client

    expect(@client.get_fitness.distance).to eq 0.5
  end
```

You can then extract those to a `before` block if you want to share the client across multiple tests.

**Comment by topher6345** [comment]
Thanks for all your help guys! It looks like I had some higher level problems that have nothing to do with the validic gem. Thanks for your great work on this project
