### ISSUE TITLE
Validic::Error::Unauthorized: 401:

### ISSUE THREAD

**Issue by diofeher** [Validic/validic#40]
2.2.4 :016 > ValidicClient.get_synced_apps(authentication_token: "mg67ygZYY5AzuJJSn4nw")
Validic::Error::Unauthorized: 401:

Guys, I keep receiving Unauthorized 401 when trying to use this method. All the other methods are working fine. I just synced one user and saved the access token and even with that I cannot access the method.

Any thoughts?

**Comment by jeff-brown-validic** [comment]
Good afternoon,

The 401s are being returned because the authentication_token you referenced is not associated with any user currently in our database.

Also, the it looks like you are using an older version (v 0.5.0) and there is a new version (v 0.5.1)

**Comment by diofeher** [comment]
Thanks @jeff-brown-validic Will check here :)
