### ISSUE TITLE
request to flex Faraday Middleware version

### ISSUE THREAD

**Issue by amf9t2** [Validic/validic#41]
Hi,

I am blocked to consume this gem due to faraday_middleware version [lock](https://github.com/Validic/validic/blob/master/Gemfile.lock#L18). 
 ```faraday_middleware (0.9.1)
      faraday (>= 0.7.4, < 0.10) ```
I would really appreciate if we make it flexible to consume latest version [0.10](https://github.com/lostisland/faraday_middleware/releases/tag/v0.10.0) and I believe it is a good practice too.

Faraday_middleware seems to respect semantic versioning so flexing based off the minor version should have no breaking changes.

Thanks.

**Comment by allcentury** [comment]
Hi @amf9t2  - Thanks for letting us know.  We're happy to upgrade the dependency and we'll likely look into removing `faraday_middleware` at a later point.  I've put in a PR and I'll circle back to this ticket when we get it merged and redeployed to rubygems.org.

In the future we welcome PR's so if you see anything else feel free to submit.  Thanks again for filing the issue.

Anthony

**Comment by amf9t2** [comment]
Thank you so much for the quick response @allcentury

**Comment by jeff-brown-validic** [comment]
Good afternoon @amf9t2,

@allcentury created the following branch: "upgrade-faraday-middleware" and opened a PR. The PR has passed all CI/Build tests but is waiting for final peer review before being merged back into master.

If you wish to move forward with you project in the short term, I would suggest pulling down the branch mentioned above.

**Comment by alex-bezek** [comment]
Hello @jeff-brown-validic ,

I had posted a comment on the mentioned pull request ( https://github.com/Validic/validic/pull/42 ), but haven't heard back. That is what @amf9t2 is waiting on a response from.

Thanks,
Alex Bezek

**Comment by jeff-brown-validic** [comment]
Good afternoon @alex-bezek,

Your comments/questions on PR #42 are being reviewed by our development team in conjunction with the approval/non-approval of the PR. As soon as they determine how they want to proceed with this I will let you know.

**Comment by amf9t2** [comment]
@jeff-brown-validic Thanks for your time and update.
