### ISSUE TITLE
use relative paths in constructing path

### ISSUE THREAD

**Issue by jonaldomo** [Validic/validic#48]
use relative paths in constructing path.  faraday ignores trailing paths in urls when the path starts with a slash.  see: https://github.com/lostisland/faraday/issues/293

example: an api_url that has a trailing path like this:

`config.api_url          = 'https://www.validic.com/api'`

will result in a call like this:

`https://www.validic.com/v1/organizations/1/apps.json`

instead of

`https://www.validic.com/api/v1/organizations/1/apps.json`

**Comment by allcentury** [comment]
Well, that's certainly a TIL but I understand why. We're using the [`Faraday::Request#url`](https://github.com/lostisland/faraday/blob/master/lib/faraday/request.rb#L48) method to build and set the path when we make the requests (the referenced Faraday ticket shows the `.get` method but I can confirm `#url` has the same behavior).  

Unit tests are still passing where we explicitly check for path correctness (ie [here](https://github.com/Validic/validic/blob/master/spec/validic/rest/fitness_spec.rb#L21)).  That said, this doesn't check host in most places but we should at least somewhere.
