### ISSUE TITLE
User calls should default to organization configured in initializer

### ISSUE THREAD

**Issue by allcentury** [Validic/validic#7]
Calls found in [lib/user.rb](https://github.com/Validic/validic/blob/master/lib/validic/user.rb) currently require an `organization_id` even though we allow for organization_id's to be set in an initializer like so:

```ruby
Validic.configure do |config|
  config.api_url        = 'https://api.validic.com'
  config.api_version    = 'v1'
  config.organization_id = ENV['VALIDIC_ORG_ID']
  config.access_token = ENV['VALIDIC_ACCESS_TOKEN']
end
```

Passing an organization should be optional

**Comment by jjlangholtz** [comment]
This issue has been resolved 6782f45.
