### ISSUE TITLE
Gem does not work with activesupport 4.x

### ISSUE THREAD

**Issue by nwise** [Validic/validic#9]
Just tried to spin up basic Ruby app with this gem. By default, the gemspec requires the latest version of activesupport (which is now 4.2.0).  This causes errors when requiring the gem.  

Fixing activesupport to ~>3.2 in my Gemfile solved the problem. Please either update the gem for the most recent activesupport or update the gemspec to only allow compatible versions.

**Comment by jjlangholtz** [comment]
We have merged in your PR that solved this problem. Just so you know we have made several changes and additions on the new 0.4.0 branch which we will now be maintaining going forward. If there are any other issues or suggestions let me know and we will be sure to update there as well.
